name: Portfolio
description: Patrick Cate's Portfolio
twitter_id: '@patrickcate'
markdown: kramdown
highlighter: pygments
relative_permalinks: false
doctor: true
url: http://portfolio.patrickcate.com

timezone: America/New_York
source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
include: ['.htaccess', 'js/*.js', '_pages']

# Serving
port: 3000
host: localhost

gems: ['jekyll_version_plugin']

sitemap:
  file: '/sitemap.xml'

# Compress layout settings
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  - project

exclude: ['*.json', '*.log', '*.map', '*.zip', 'js/**/*.*', 'gulpfile.js', 'node_modules', 'sass', 'Gemfile', 'Gemfile.lock']
